/**
 * Model of the loop sent to the Pogues API's loops endpoint, which creates the
 * loop if no loop has this id in the questionnaire and updates it otherwise.
 */
export type LoopDTO = {
  /** Id of the loop, generated by the front-end when it is created. */
  id: string
  name: string
  /** Id of the first component repeated by the loop. */
  initialMember: string
  /** Id of the last component repeated by the loop. */
  finalMember: string
} & (
  | {
      /** Id of the scope whose occurrences are repeated. */
      basedOn: string
      /** VTL formula filtering the occurrences. */
      filter?: string
    }
  | {
      isFixedLength: true
      /** VTL formula of the number of occurrences. */
      size: string
      /** Whether each occurrence is displayed on its own page. */
      shouldSplitIterations: boolean
    }
  | {
      isFixedLength: false
      /** VTL formula of the minimum number of occurrences. */
      minimum: string
      /** VTL formula of the maximum number of occurrences. */
      maximum: string
      addButtonLabel?: string
    }
)
