module.exports = [
  {
    id: "campaign01",
    label: "Campaign 01",
    parent: "operation01",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign02",
    label: "Campaign 02",
    parent: "operation01",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign03",
    label: "Campaign 03",
    parent: "operation02",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign04",
    label: "Campaign 04",
    parent: "operation02",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign05",
    label: "Campaign 05",
    parent: "operation03",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign06",
    label: "Campaign 06",
    parent: "operation03",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign07",
    label: "Campaign 07",
    parent: "operation04",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign08",
    label: "Campaign 08",
    parent: "operation04",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign09",
    label: "Campaign 09",
    parent: "operation05",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign10",
    label: "Campaign 10",
    parent: "operation05",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign11",
    label: "Campaign 11",
    parent: "operation06",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign12",
    label: "Campaign 12",
    parent: "operation06",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign13",
    label: "Campaign 13",
    parent: "operation07",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign14",
    label: "Campaign 14",
    parent: "operation07",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign01",
    label: "Campaign 01",
    parent: "operation08",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign02",
    label: "Campaign 02",
    parent: "operation08",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign03",
    label: "Campaign 03",
    parent: "operation09",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign04",
    label: "Campaign 04",
    parent: "operation09",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign05",
    label: "Campaign 05",
    parent: "operation10",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign06",
    label: "Campaign 06",
    parent: "operation10",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign07",
    label: "Campaign 07",
    parent: "operation11",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign08",
    label: "Campaign 08",
    parent: "operation11",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign09",
    label: "Campaign 09",
    parent: "operation12",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign10",
    label: "Campaign 10",
    parent: "operation12",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign11",
    label: "Campaign 11",
    parent: "operation13",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign12",
    label: "Campaign 12",
    parent: "operation13",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign13",
    label: "Campaign 13",
    parent: "operation14",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
  {
    id: "campaign14",
    label: "Campaign 14",
    parent: "operation14",
    groupId:null,
    subGroupId:null,
    studyUnitId:null,
    dataCollectionId:null,
    resourcePackageId:null,
    type:"DataCollection",
  },
];
