import { describe, expect, test } from 'vitest';

import { CodeList, RemoteCodeList } from '@/models/code-lists';

import { listCodes } from './__mocks__/codes-lists-utils';
import {
  hasChild,
  isNomenclatureCodeList,
  isNomenclatureRemoteCodeList,
} from './codes-lists-utils';

describe('Codes lists utils', () => {
  test('hasChild should return false', () => {
    expect(hasChild({ value: '2' }, listCodes)).toBeFalsy();
  });
  test('hasChild should return true', () => {
    expect(hasChild({ value: '1' }, listCodes)).toBeTruthy();
  });
});

/**
 * Theses tests are generated by A.I
 */
describe('isNomenclatureCodeList', () => {
  it('should return true if urn is defined', () => {
    const codeList: CodeList = { id: '1', urn: 'urn:test' };
    expect(isNomenclatureCodeList(codeList)).toBe(true);
  });

  it('should return true if suggesterParameters is defined', () => {
    const codeList: CodeList = { id: '1', suggesterParameters: {} };
    expect(isNomenclatureCodeList(codeList)).toBe(true);
  });

  it('should return true if both urn and suggesterParameters are defined', () => {
    const codeList: CodeList = {
      id: '1',
      urn: 'urn:test',
      suggesterParameters: {},
    };
    expect(isNomenclatureCodeList(codeList)).toBe(true);
  });

  it('should return false if neither urn nor suggesterParameters are defined', () => {
    const codeList: CodeList = { id: '1' };
    expect(isNomenclatureCodeList(codeList)).toBe(false);
  });

  it('should return false if urn is null', () => {
    const codeList: CodeList = { id: '1', urn: null };
    expect(isNomenclatureCodeList(codeList)).toBe(false);
  });

  it('should return false if suggesterParameters is null', () => {
    const codeList: CodeList = { id: '1', suggesterParameters: null };
    expect(isNomenclatureCodeList(codeList)).toBe(false);
  });

  it('should return false if urn is undefined', () => {
    const codeList: CodeList = { id: '1', urn: undefined };
    expect(isNomenclatureCodeList(codeList)).toBe(false);
  });
});

describe('isNomenclatureRemoteCodeList', () => {
  it('should return true if Urn is defined', () => {
    const codeList: RemoteCodeList = { id: '1', Urn: 'urn:test' };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(true);
  });

  it('should return true if SuggesterParameters is defined', () => {
    const codeList: RemoteCodeList = { id: '1', SuggesterParameters: {} };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(true);
  });

  it('should return true if both Urn and SuggesterParameters are defined', () => {
    const codeList: RemoteCodeList = {
      id: '1',
      Urn: 'urn:test',
      SuggesterParameters: {},
    };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(true);
  });

  it('should return false if neither Urn nor SuggesterParameters are defined', () => {
    const codeList: RemoteCodeList = { id: '1' };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(false);
  });

  it('should return false if Urn is null', () => {
    const codeList: RemoteCodeList = { id: '1', Urn: null };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(false);
  });

  it('should return false if SuggesterParameters is null', () => {
    const codeList: RemoteCodeList = { id: '1', SuggesterParameters: null };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(false);
  });

  it('should return false if Urn is undefined', () => {
    const codeList: RemoteCodeList = { id: '1', Urn: undefined };
    expect(isNomenclatureRemoteCodeList(codeList)).toBe(false);
  });
});
